/*
 Copyright 2012 - Syu Kato <ukyo.web@gmail.com>
 mp4.js
 Licensed under the Apache License, Version 2.0 (the "License");
 http://www.apache.org/licenses/LICENSE-2.0
*/
var mp4=mp4||{};mp4.utils=mp4.utils||{};
(function(){var s=this;this.isType=function(a,b){return null!=a?a.constructor==b:!1};this.load=function(a,b){var f=new XMLHttpRequest;f.open("GET",a);f.responseType="arraybuffer";f.onreadystatechange=function(){if(4==f.readyState)if(2===~~(f.status/100)||0===f.status)b.call(f,f.response);else throw"Error: "+f.status;};f.send()};this.getUi16=function(a,b){return a[b]<<8|a[b+1]};this.getUi24=function(a,b){return a[b+1]<<16|a[b]<<8|a[b+1]};this.getUi32=function(a,b){return a[b]<<24|a[b+1]<<16|a[b+2]<<
8|a[b+3]};this.getStr=function(a,b,f){for(var c=[],g=0;g<b;++g)c[c.length]=a[f+g];return String.fromCharCode.apply(null,c)};this.putUi16=function(a,b,f){a[f+1]=b&255;a[f]=b>>8};this.putUi24=function(a,b,f){a[f+2]=b&255;a[f+1]=b>>8&255;a[f]=b>>16};this.putUi32=function(a,b,f){a[f+3]=b&255;a[f+2]=b>>8&255;a[f+1]=b>>16&255;a[f]=b>>24};this.putStr=function(a,b,f){for(var c=0,g=b.length;c<g;++c)a[c+f]=b.charCodeAt(c)};this.concatByteArrays=function(a){var a=s.isType(a,Array)?a:Array.prototype.slice.call(arguments,
0),b=0,f=0,c,g;for(c=0,g=a.length;c<g;++c)b+=a[c].length;b=new Uint8Array(b);for(c=0;c<g;++c)b.set(a[c],f),f+=a[c].length;return b}}).call(mp4.utils,this);mp4=mp4||{};mp4.descr=mp4.descr||{};
(function(s,a){var b=this,f=a.putUi16,c=a.putUi24,g=a.putUi32,r=a.putStr,q=a.isType,i=a.concatByteArrays;this.createBaseDescriptor=function(b,a){var k=new Uint8Array(b+2);k[0]=a;k[1]=b;return k};this.createESDescriptor=function(a,d,k,h,c,w,n){var g="string"===typeof h?1:0,o=null!=k?1:0,j=3,l=2,n=null==n?[]:q(n,Array)?n:[n],j=j+(o?2:0)+(g?h.length+1:0),j=j+c.length,j=j+w.length,n=i(n),j=j+n.length,j=b.createBaseDescriptor(j,3);f(j,a,l);l+=2;j[l++]=o<<7|g<<6|d;o&&(f(j,k,l),l+=2);g&&(j[l++]=h.length,
r(j,h,l),l+=h.length);j.set(c,l);l+=c.length;j.set(w,l);l+=w.length;j.set(n,l);return j};this.createDecodeConfigDescriptor=function(a,d,k,h,x,w,n){var f,n=null==n?[]:q(n,Array)?n:[n];f=i(n);n=b.createBaseDescriptor(f.length+13,4);n[2]=a;n[3]=d<<2|k<<1|1;c(n,h,4);g(n,x,7);g(n,w,11);n.set(f,15);return n};this.createDecoderSpecificInfo=function(a){var q=b.createBaseDescriptor(a.length,5);r(q,a,2);return q};this.createSLConfigDescriptor=function(a){var q=b.createBaseDescriptor(1,6);q[2]=a;return q};this.createInitialObjectDescriptor=
function(a,c,k,h,x,w,n,g,o,j){var l="string"===typeof k?1:0,m=2,p=4,o=null==o?[]:q(o,Array)?subDescr:[subDescr],j=null==j?[]:q(j,Array)?extDescr:[extDescr],m=m+(l?k.length+1:5),j=i(j),m=m+j.length;l?(m=b.createBaseDescriptor(m,16),m[p++]=k.length,r(m,k,p)):(k=i(o),m+=k.length,m=b.createBaseDescriptor(m,16),m[p++]=h,m[p++]=x,m[p++]=w,m[p++]=n,m[p++]=g,m.set(k,p));p+=k.length;f(m,a<<6|l<<5|c<<4|15,2);m.set(j,p);return m}}).call(mp4.descr,this,mp4.utils);mp4=mp4||{};mp4.box=mp4.box||{};
(function(s,a){var b=this,f=a.putUi16,c=a.putUi32,g=a.putStr,r=a.concatByteArrays;this.createBox=function(b,a){var e=new Uint8Array(b);c(e,b,0);g(e,a,4);return e};this.createFullBox=function(a,i,c,d){a=b.createBox(a,i);f(a,c,8);f(a,d,10);return a};this.createMp4aBox=function(a,c,e){var d=b.createBox(36+e.length,"mp4a");f(d,a,14);f(d,2,24);f(d,16,26);f(d,c,32);d.set(e,36);return d};this.createEsdsBox=function(a){var c=b.createFullBox(12+a.length,"esds",0,0);c.set(a,12);return c};this.createTkhdBox=
function(a,i,e,d,k){var h=b.createFullBox(92,"tkhd",0,1);c(h,a,12);c(h,i,16);c(h,e,20);c(h,d,28);f(h,!k?256:0,44);c(h,65536,48);c(h,65536,64);c(h,1073741824,80);c(h,k?20971520:0,84);c(h,k?15728640:0,88);return h};this.createMdhdBox=function(a,i,e,d){var k=b.createFullBox(32,"mdhd",0,0);c(k,a,12);c(k,i,16);c(k,e,20);c(k,d,24);f(k,21956,28);return k};this.createHdlrBox=function(a,c){var e=b.createFullBox(32+c.length+1,"hdlr",0,0);g(e,a,16);g(e,c,32);return e};this.concatBoxes=function(a,c){var c=Array.prototype.slice.call(arguments,
1),a=arguments[0],e,d;d=r(c);e=b.createBox(d.length+8,a);e.set(d,8);return e};this.createUrlBox=function(a,c){var e="string"===typeof a?a.length+1:0,d=b.createFullBox(12+e,"url ",0,"undefined"===typeof c?1:c);e&&g(d,a,12);return d};this.createUrnBox=function(a,b,c){return createUrlBox(a+"\x00"+b,c)};this.createDrefBox=function(a){var a=Array.prototype.slice.call(arguments,0),i,e;e=r(a);i=b.createFullBox(e.length+16,"dref",0,0);c(i,12,a.length);i.set(e,16);return i};this.createStszBox=function(a,i){var e=
b.createFullBox(20+4*i.length,"stsz",0,0),d,k;c(e,a,12);c(e,i.length,16);if(0===a)for(d=0,k=i.length;d<k;++d)c(e,i[d],4*d+20);return e};this.createMvhdBox=function(a,i,e,d,k){var h=b.createFullBox(108,"mvhd",0,0);c(h,a,12);c(h,i,16);c(h,e,20);c(h,d,24);c(h,65536,28);f(h,256,32);c(h,65536,44);c(h,65536,60);c(h,1073741824,76);c(h,k,104);return h};this.createIodsBox=function(a){var c=b.createFullBox(a.length+12,"iods",0,0);c.set(a,12);return c};this.createDinfBox=function(a){var a=Array.prototype.slice.call(arguments,
0),i=16,e=16,d,k,h;for(d=0,k=a.length;d<k;++d)i+=a[d].length;h=b.createFullBox(i,"dref",0,0);c(h,k,12);for(d=0;d<k;++d)h.set(a[d],e),e+=a[d].length;i=b.createBox(i+8,"dinf");i.set(h,8);return i};this.createStsdBox=function(a){var a=Array.prototype.slice.call(arguments,0),i,e;e=r(a);i=b.createFullBox(e.length+16,"stsd",0,0);c(i,a.length,12);i.set(e,16);return i};this.createSttsBox=function(a){var i=b.createFullBox(16+8*a.length,"stts",0,0),e=16,d,k;c(i,a.length,12);for(d=0,k=a.length;d<k;++d)c(i,a[d].count,
e),c(i,a[d].duration,e+4),e+=8;return i};this.createStscBox=function(a,i){var e=b.createFullBox(40,"stsc",0,0);c(e,2,12);c(e,1,16);c(e,i,20);c(e,1,24);c(e,~~(a/i)+1,28);c(e,a%i,32);c(e,1,36);return e};this.createStcoBox=function(a){var i=a.length,e=b.createFullBox(16+4*i,"stco",0,0),d;c(e,i,12);for(d=0;d<i;++d)c(e,a[d],4*d+16);return e};this.createFreeBox=function(a){var c=b.createBox(8+a.length+1,"free");g(c,a,8);return c};this.createFtypBox=function(a,c){var e=Array.prototype.slice.call(arguments,
0),d=b.createBox(4*e.length+16,"ftyp"),k=16,h,x;g(d,a,8);for(h=0,x=e.length;h<x;++h)g(d,e[h],k),k+=4;return d}}).call(mp4.box,this,mp4.utils);mp4=mp4||{};
(function(s,a){function b(a,h,b){for(var c,d={size:b},f=h+b,i,h=h+8;h<f;){b=g(a,h);c=r(a,4,h+4);if(i=e[c])d[c]&&!q(d[c],Array)?(d[c]=[d[c]],d[c].push(i(a,h,b))):q(d[c],Array)?d[c].push(i(a,h,b)):d[c]=i(a,h,b);else break;h+=b}return d}a.version="0.1";var f=s.MozBlobBuilder||s.WebKitBlobBuilder||s.MSBlobBuilder||s.BlobBuilder,c=a.utils.getUi16,g=a.utils.getUi32,r=a.utils.getStr,q=a.utils.isType,i=a.utils.concatByteArrays,e={ID32:b,albm:function(){},auth:function(){},bpcc:function(){},buff:function(){},bxml:b,
ccid:function(){},cdef:function(){},clsf:function(){},cmap:function(){},co64:function(){},colr:function(){},cprt:function(){},crhd:function(){},cslg:function(){},ctts:function(a,h,b){var b={size:b,body:[]},c,d=g(a,h+=12);for(c=0;c<d;++c)b.body.push({compositionOffset:g(a,h+=4),sampleCount:g(a,h+=4)});return b},cvru:function(){},dcfD:function(){},dinf:b,dref:b,dscp:function(){},dsgd:b,dstg:b,edts:b,elst:function(){},feci:function(){},fecr:function(){},fiin:function(){},fire:function(){},fpar:function(){},
free:function(){},frma:b,ftyp:function(){},gitn:function(){},gnre:function(){},grpi:function(){},hdlr:function(a,b,c){return{size:c,type:r(a,4,b+16)}},hmhd:function(){},hpix:function(){},icnu:function(){},idat:function(){},ihdr:function(){},iinf:function(){},iloc:function(){},imif:b,infu:function(){},iods:b,iphd:function(){},ipmc:b,ipro:function(){},iref:function(){},"jp  ":function(){},jp2c:function(){},jp2h:function(){},jp2i:function(){},kywd:function(){},loci:function(){},lrcu:function(){},m7hd:function(){},
mdat:function(a,b,c){return{offset:b,size:c,dataSize:c-8}},mdhd:function(a,b,c){return{size:c,creationTime:g(a,b+12),modificationTime:g(a,b+16),timeScale:g(a,b+20),duration:g(a,b+24),languageCode:g(a,b+28)}},mdia:b,mdri:function(){},meco:b,mehd:b,mere:function(){},meta:b,mfhd:function(){},mfra:function(){},mfro:function(){},minf:b,mjhd:function(){},moof:function(){},moov:b,mvcg:function(){},mvci:function(){},mvex:b,mvhd:function(){},mvra:function(){},nmhd:function(){},ochd:function(){},odaf:function(){},
odda:function(){},odhd:function(){},odhe:function(){},odrb:function(){},odrm:b,odtt:function(){},ohdr:function(){},padb:function(){},paen:function(){},pclr:function(){},pdin:function(){},perf:function(){},pitm:function(){},"res ":function(){},resc:function(){},resd:function(){},rtng:function(){},sbgp:b,schi:b,schm:b,sdep:function(){},sdhd:function(){},sdtp:b,sdvp:b,segr:function(){},sgpd:b,sidx:b,sinf:b,skip:function(){},smhd:function(){},srmb:function(){},srmc:b,srpp:function(){},stbl:b,stco:function(a,
b,c){var c={size:c,body:[]},d,e=g(a,b+=12);for(d=0;d<e;++d)c.body.push(g(a,b+=4));return c},stdp:function(){},stsc:function(a,b,c){var c={size:c,body:[]},d,e=g(a,b+=12);for(d=0;d<e;++d)c.body.push({firstChunk:g(a,b+=4),samplesPerChunk:g(a,b+=4),sampleDescriptionIndex:g(a,b+=4)});return c},stsd:function(a,c,d){return b(a,c+8,d-8)},stsh:function(){},stss:function(){},stts:function(a,b,c){return{size:c,entryCount:g(a,b+12),sampleCount:g(a,b+16),sampleDelta:g(a,b+20)}},styp:b,stsz:function(a,b,c){var c=
{size:c,body:[]},d,e=g(a,b+=16);for(d=0;d<e;++d)c.body.push(g(a,b+=4));return c},stz2:function(){},subs:function(){},swtc:function(){},tfad:b,tfhd:function(){},tfma:b,tfra:function(){},tibr:function(){},tiri:function(){},titl:function(){},tkhd:function(){},traf:function(){},trak:b,tref:b,trex:function(){},trgr:function(){},trun:function(){},tsel:function(){},udta:b,uinf:function(){},UITS:function(){},ulst:function(){},"url ":function(){},vmhd:function(){},vwdi:function(){},"xml ":function(){},yrrc:function(){},
mp4a:function(a,b){return{dataReferenceIndex:g(a,b+=12),channels:c(a,b+=12),bitPerSample:c(a,b+=2),sampleRate:g(a,b+=4),esds:{objectTypeIndication:a[b+=25],bufferSizeDB:c(a,b+=3),maxBitrate:g(a,b+=2),avgBitrate:g(a,b+4)}}}},d=[96E3,88200,64E3,48E3,44100,32E3,24E3,22050,16E3,12E3,11025,8E3];a.Parser=function(a){this.bytes=q(a,ArrayBuffer)?new Uint8Array(a):a;this.cache={}};a.Parser.prototype={parse:function(){return this.cache.tree?this.cache.tree:this.cache.tree=b(this.bytes,-8,this.bytes.length)},
extractAACAsArrayBuffer:function(){var a=this.parse().moov.trak,b,c,e,i,f,g,j,l,m,p,r,y,s,u=0,v=0,t=new Uint8Array(new ArrayBuffer(7));if(q(a,Array))a.forEach(function(a){"soun"===a.mdia.hdlr.type&&(b=a)});else if("soun"===a.mdia.hdlr.type)b=a;else throw"This file does not have audio files.";a=b.mdia.minf.stbl.stsd.mp4a;c=b.mdia.minf.stbl.stsc.body;e=b.mdia.minf.stbl.stsz.body;i=b.mdia.minf.stbl.stco.body;s=new Uint8Array(7*e.length+e.reduce(function(a,b){return a+b}));t[0]=255;t[1]=249;t[2]=64|d.indexOf(a.sampleRate)<<
2|a.channels>>2;t[6]=252;for(f=0,y=0,l=c.length;f<l;++f){g=c[f].firstChunk-1;for(m=f+1<l?c[f+1].firstChunk-1:i.length;g<m;++g){v=i[g];for(j=0,p=c[f].samplesPerChunk;j<p;++j,++y)r=e[y]+7,t[3]=a.channels<<6|r>>11,t[4]=r>>3,t[5]=r<<5|31,s.set(t,u),u+=7,s.set(this.bytes.subarray(v,v+=e[y]),u),u+=e[y]}}return s.buffer},extractAACAsBlob:function(){var a=new f;a.append(this.extractAACAsArrayBuffer());return a.getBlob("audio/aac")}};a.aacToM4a=function(b){function c(a){return(e[a+3]&3)<<11|e[a+4]<<3|e[a+
5]>>5}var e=new Uint8Array(b),f=0,b=0,g=[],r=[],o=Date.now(),j,l,m,p,q,s,z,u,v,t,A,B;for(l=d[(e[2]&60)>>2];f<e.length;)r[b]=f,g[b++]=c(f)-7,f+=c(f);j=b;p=a.descr.createInitialObjectDescriptor(1,0,null,255,255,41,255,255);f=a.descr.createDecoderSpecificInfo("\u0012\u0010");m=a.descr.createDecodeConfigDescriptor(103,5,0,367,0,0,[f]);f=a.descr.createSLConfigDescriptor(2);f=a.descr.createESDescriptor(0,0,null,null,m,f,[]);f=a.box.createEsdsBox(f);m=a.box.createMp4aBox(1,l,f);f=a.box.createFtypBox("M4A ",
"isom","mp42");q=a.box.createSttsBox([{count:b,duration:1024}]);s=a.box.createStscBox(b,j);z=a.box.createStszBox(0,g);u=a.box.createStsdBox(m);v=a.box.createDinfBox(a.box.createUrlBox(null,1));t=a.box.createBox(16,"smhd");A=a.box.createMdhdBox(o,o,l,1024*b);B=a.box.createHdlrBox("soun","mp4.js Audio Handler");m=a.box.createTkhdBox(o,o,1,~~(614400*b/l));p=a.box.createIodsBox(p);l=a.box.createMvhdBox(o,o,600,~~(614400*b/l),2);o=g.reduce(function(a,b){return a+b});dataStart=f.length+q.length+s.length+
z.length+u.length+v.length+t.length+A.length+B.length+m.length+p.length+l.length;dataStart+=48;dataStart+=4*(~~(g.length/j)+1)+16;j=a.box.createStcoBox([dataStart,dataStart+o]);j=a.box.concatBoxes("stbl",u,q,s,z,j);j=a.box.concatBoxes("minf",t,v,j);j=a.box.concatBoxes("mdia",A,B,j);j=a.box.concatBoxes("trak",m,j);moov=a.box.concatBoxes("moov",l,p,j);j=a.box.createBox(o+8,"mdat");o=0;l=8;for(m=0;m<b;++m)o=r[m],j.set(e.subarray(o+7,o+7+g[m]),l),l+=g[m];b=a.box.createFreeBox("Produced with mp4.js "+
a.version);return i(f,moov,j,b).buffer}})(this,mp4);
