/*
 mp4.js Copyright 2012 - Syu Kato <ukyo.web@gmail.com>
 @version 0.2
 Licensed under the Apache License, Version 2.0 (the "License");
 http://www.apache.org/licenses/LICENSE-2.0
*/
var mp4js=mp4js||{};mp4js.version="0.2";(function(){var i=this;this.isType=function(a,e){return null!=a?a.constructor==e:!1};this.load=function(a,e){var h=new XMLHttpRequest;h.open("GET",a);h.responseType="arraybuffer";h.onreadystatechange=function(){if(4==h.readyState)if(2===~~(h.status/100)||0===h.status)e.call(h,h.response);else throw"Error: "+h.status;};h.send()};this.getUi16=function(a,e){return a[e]<<8|a[e+1]};this.getUi24=function(a,e){return a[e+1]<<16|a[e]<<8|a[e+1]};this.getUi32=function(a,e){return a[e]<<24|a[e+1]<<16|a[e+2]<<
8|a[e+3]};this.getStr=function(a,e,h){for(var c=[],i=0;i<e;++i)c[c.length]=a[h+i];return String.fromCharCode.apply(null,c)};this.putUi16=function(a,e,h){a[h+1]=e&255;a[h]=e>>8};this.putUi24=function(a,e,h){a[h+2]=e&255;a[h+1]=e>>8&255;a[h]=e>>16};this.putUi32=function(a,e,h){a[h+3]=e&255;a[h+2]=e>>8&255;a[h+1]=e>>16&255;a[h]=e>>24};this.putStr=function(a,e,h){for(var c=0,i=e.length;c<i;++c)a[c+h]=e.charCodeAt(c)};this.concatByteArrays=function(a){var a=i.isType(a,Array)?a:Array.prototype.slice.call(arguments,
0),e=0,h=0,c,q;for(c=0,q=a.length;c<q;++c)e+=a[c].length;e=new Uint8Array(e);for(c=0;c<q;++c)e.set(a[c],h),h+=a[c].length;return e}}).call(function(i){i=i||{};i.utils=i.utils||{};return i.utils}(this.mp4js),this);var mp4=mp4||{};mp4.descr=mp4.descr||{};
(function(i,a){var e=this,h=a.putUi16,c=a.putUi24,q=a.putUi32,n=a.putStr,s=a.isType,j=a.concatByteArrays;this.createBaseDescriptor=function(f,b){var g=new Uint8Array(f+2);g[0]=b;g[1]=f;return g};this.createESDescriptor=function(f,b,g,d,a,c,o){var i="string"===typeof d?1:0,p=null!=g?1:0,k=3,l=2,o=null==o?[]:s(o,Array)?o:[o],k=k+(p?2:0)+(i?d.length+1:0),k=k+a.length,k=k+c.length,o=j(o),k=k+o.length,k=e.createBaseDescriptor(k,3);h(k,f,l);l+=2;k[l++]=p<<7|i<<6|b;p&&(h(k,g,l),l+=2);i&&(k[l++]=d.length,
n(k,d,l),l+=d.length);k.set(a,l);l+=a.length;k.set(c,l);l+=c.length;k.set(o,l);return k};this.createDecodeConfigDescriptor=function(f,b,g,d,a,h,o){var i,o=null==o?[]:s(o,Array)?o:[o];i=j(o);o=e.createBaseDescriptor(i.length+13,4);o[2]=f;o[3]=b<<2|g<<1|1;c(o,d,4);q(o,a,7);q(o,h,11);o.set(i,15);return o};this.createDecoderSpecificInfo=function(f){var b=e.createBaseDescriptor(f.length,5);b.set(f,2);return b};this.createSLConfigDescriptor=function(f){var b=e.createBaseDescriptor(1,6);b[2]=f;return b};
this.createInitialObjectDescriptor=function(f,b,g,d,a,c,o,i,p,k){var l="string"===typeof g?1:0,m=2,r=4,p=null==p?[]:s(p,Array)?subDescr:[subDescr],k=null==k?[]:s(k,Array)?extDescr:[extDescr],m=m+(l?g.length+1:5),k=j(k),m=m+k.length;l?(m=e.createBaseDescriptor(m,16),m[r++]=g.length,n(m,g,r)):(g=j(p),m+=g.length,m=e.createBaseDescriptor(m,16),m[r++]=d,m[r++]=a,m[r++]=c,m[r++]=o,m[r++]=i,m.set(g,r));r+=g.length;h(m,f<<6|l<<5|b<<4|15,2);m.set(k,r);return m}}).call(function(i){i=i||{};i.descr=i.descr||
{};return i.descr}(this.mp4js),this,this.mp4js.utils);(function(i,a){var e=this,h=a.putUi16,c=a.putUi32,q=a.putStr,n=a.concatByteArrays;this.createBox=function(a,j){var f=new Uint8Array(a);c(f,a,0);q(f,j,4);return f};this.createFullBox=function(a,c,f,b){a=e.createBox(a,c);h(a,f,8);h(a,b,10);return a};this.createMp4aBox=function(a,c,f){var b=e.createBox(36+f.length,"mp4a");h(b,a,14);h(b,2,24);h(b,16,26);h(b,c,32);b.set(f,36);return b};this.createEsdsBox=function(a){var c=e.createFullBox(12+a.length,"esds",0,0);c.set(a,12);return c};this.createTkhdBox=
function(a,j,f,b,g){var d=e.createFullBox(92,"tkhd",0,1);c(d,a,12);c(d,j,16);c(d,f,20);c(d,b,28);h(d,!g?256:0,44);c(d,65536,48);c(d,65536,64);c(d,1073741824,80);c(d,g?20971520:0,84);c(d,g?15728640:0,88);return d};this.createMdhdBox=function(a,j,f,b){var g=e.createFullBox(32,"mdhd",0,0);c(g,a,12);c(g,j,16);c(g,f,20);c(g,b,24);h(g,21956,28);return g};this.createHdlrBox=function(a,c){var f=e.createFullBox(32+c.length+1,"hdlr",0,0);q(f,a,16);q(f,c,32);return f};this.concatBoxes=function(a,c){var c=Array.prototype.slice.call(arguments,
1),a=arguments[0],f,b;b=n(c);f=e.createBox(b.length+8,a);f.set(b,8);return f};this.createUrlBox=function(a,c){var f="string"===typeof a?a.length+1:0,b=e.createFullBox(12+f,"url ",0,"undefined"===typeof c?1:c);f&&q(b,a,12);return b};this.createUrnBox=function(a,c,f){return createUrlBox(a+"\x00"+c,f)};this.createDrefBox=function(a){var a=Array.prototype.slice.call(arguments,0),j,f;f=n(a);j=e.createFullBox(f.length+16,"dref",0,0);c(j,12,a.length);j.set(f,16);return j};this.createStszBox=function(a,j){var f=
e.createFullBox(20+4*j.length,"stsz",0,0),b,g;c(f,a,12);c(f,j.length,16);if(0===a)for(b=0,g=j.length;b<g;++b)c(f,j[b],4*b+20);return f};this.createMvhdBox=function(a,j,f,b,g){var d=e.createFullBox(108,"mvhd",0,0);c(d,a,12);c(d,j,16);c(d,f,20);c(d,b,24);c(d,65536,28);h(d,256,32);c(d,65536,44);c(d,65536,60);c(d,1073741824,76);c(d,g,104);return d};this.createIodsBox=function(a){var c=e.createFullBox(a.length+12,"iods",0,0);c.set(a,12);return c};this.createDinfBox=function(a){var a=Array.prototype.slice.call(arguments,
0),j=16,f=16,b,g,d;for(b=0,g=a.length;b<g;++b)j+=a[b].length;d=e.createFullBox(j,"dref",0,0);c(d,g,12);for(b=0;b<g;++b)d.set(a[b],f),f+=a[b].length;j=e.createBox(j+8,"dinf");j.set(d,8);return j};this.createStsdBox=function(a){var a=Array.prototype.slice.call(arguments,0),j,f;f=n(a);j=e.createFullBox(f.length+16,"stsd",0,0);c(j,a.length,12);j.set(f,16);return j};this.createSttsBox=function(a){var j=e.createFullBox(16+8*a.length,"stts",0,0),f=16,b,g;c(j,a.length,12);for(b=0,g=a.length;b<g;++b)c(j,a[b].count,
f),c(j,a[b].duration,f+4),f+=8;return j};this.createStscBox=function(a,j){var f=e.createFullBox(40,"stsc",0,0);c(f,2,12);c(f,1,16);c(f,j,20);c(f,1,24);c(f,~~(a/j)+1,28);c(f,a%j,32);c(f,1,36);return f};this.createStcoBox=function(a){var j=a.length,f=e.createFullBox(16+4*j,"stco",0,0),b;c(f,j,12);for(b=0;b<j;++b)c(f,a[b],4*b+16);return f};this.createFreeBox=function(a){var c=e.createBox(8+a.length+1,"free");q(c,a,8);return c};this.createFtypBox=function(a,c){var f=Array.prototype.slice.call(arguments,
0),b=e.createBox(4*f.length+16,"ftyp"),g=16,d,h;q(b,a,8);for(d=0,h=f.length;d<h;++d)q(b,f[d],g),g+=4;return b}}).call(function(i){i=i||{};i.box=i.box||{};return i.box}(this.mp4js),this,this.mp4js.utils);(function(i){function a(a,b,g){for(var d,e={size:g},h=b+g,j,b=b+8;b<h;){g=c(a,b);d=n(a,4,b+4);if(j=boxes[d])e[d]&&!s(e[d],Array)?(e[d]=[e[d]],e[d].push(j(a,b,g))):s(e[d],Array)?e[d].push(j(a,b,g)):e[d]=j(a,b,g);else break;b+=g}return e}var e=i.MozBlobBuilder||i.WebKitBlobBuilder||i.MSBlobBuilder||i.BlobBuilder,h=this.utils.getUi16,c=this.utils.getUi32,q=this.utils.putUi16,n=this.utils.getStr,s=this.utils.isType,j=this.utils.concatByteArrays;self=this;boxes={ID32:a,albm:function(){},auth:function(){},
bpcc:function(){},buff:function(){},bxml:a,ccid:function(){},cdef:function(){},clsf:function(){},cmap:function(){},co64:function(){},colr:function(){},cprt:function(){},crhd:function(){},cslg:function(){},ctts:function(a,b,g){var g={size:g,body:[]},d,e=c(a,b+=12);for(d=0;d<e;++d)g.body.push({compositionOffset:c(a,b+=4),sampleCount:c(a,b+=4)});return g},cvru:function(){},dcfD:function(){},dinf:a,dref:a,dscp:function(){},dsgd:a,dstg:a,edts:a,elst:function(){},feci:function(){},fecr:function(){},fiin:function(){},
fire:function(){},fpar:function(){},free:function(){},frma:a,ftyp:function(){},gitn:function(){},gnre:function(){},grpi:function(){},hdlr:function(a,b,c){return{size:c,type:n(a,4,b+16)}},hmhd:function(){},hpix:function(){},icnu:function(){},idat:function(){},ihdr:function(){},iinf:function(){},iloc:function(){},imif:a,infu:function(){},iods:a,iphd:function(){},ipmc:a,ipro:function(){},iref:function(){},"jp  ":function(){},jp2c:function(){},jp2h:function(){},jp2i:function(){},kywd:function(){},loci:function(){},
lrcu:function(){},m7hd:function(){},mdat:function(a,b,c){return{offset:b,size:c,dataSize:c-8}},mdhd:function(a,b,g){return{size:g,creationTime:c(a,b+12),modificationTime:c(a,b+16),timeScale:c(a,b+20),duration:c(a,b+24),languageCode:c(a,b+28)}},mdia:a,mdri:function(){},meco:a,mehd:a,mere:function(){},meta:a,mfhd:function(){},mfra:function(){},mfro:function(){},minf:a,mjhd:function(){},moof:function(){},moov:a,mvcg:function(){},mvci:function(){},mvex:a,mvhd:function(){},mvra:function(){},nmhd:function(){},
ochd:function(){},odaf:function(){},odda:function(){},odhd:function(){},odhe:function(){},odrb:function(){},odrm:a,odtt:function(){},ohdr:function(){},padb:function(){},paen:function(){},pclr:function(){},pdin:function(){},perf:function(){},pitm:function(){},"res ":function(){},resc:function(){},resd:function(){},rtng:function(){},sbgp:a,schi:a,schm:a,sdep:function(){},sdhd:function(){},sdtp:a,sdvp:a,segr:function(){},sgpd:a,sidx:a,sinf:a,skip:function(){},smhd:function(){},srmb:function(){},srmc:a,
srpp:function(){},stbl:a,stco:function(a,b,g){var g={size:g,body:[]},d,e=c(a,b+=12);for(d=0;d<e;++d)g.body.push(c(a,b+=4));return g},stdp:function(){},stsc:function(a,b,g){var g={size:g,body:[]},d,e=c(a,b+=12);for(d=0;d<e;++d)g.body.push({firstChunk:c(a,b+=4),samplesPerChunk:c(a,b+=4),sampleDescriptionIndex:c(a,b+=4)});return g},stsd:function(f,b,c){return a(f,b+8,c-8)},stsh:function(){},stss:function(){},stts:function(a,b,g){return{size:g,entryCount:c(a,b+12),sampleCount:c(a,b+16),sampleDelta:c(a,
b+20)}},styp:a,stsz:function(a,b,g){var g={size:g,body:[]},d,e=c(a,b+=16);for(d=0;d<e;++d)g.body.push(c(a,b+=4));return g},stz2:function(){},subs:function(){},swtc:function(){},tfad:a,tfhd:function(){},tfma:a,tfra:function(){},tibr:function(){},tiri:function(){},titl:function(){},tkhd:function(){},traf:function(){},trak:a,tref:a,trex:function(){},trgr:function(){},trun:function(){},tsel:function(){},udta:a,uinf:function(){},UITS:function(){},ulst:function(){},"url ":function(){},vmhd:function(){},
vwdi:function(){},"xml ":function(){},yrrc:function(){},mp4a:function(a,b){return{dataReferenceIndex:c(a,b+=12),channels:h(a,b+=12),bitPerSample:h(a,b+=2),sampleRate:c(a,b+=4),esds:{objectTypeIndication:a[b+=25],bufferSizeDB:h(a,b+=3),maxBitrate:c(a,b+=2),avgBitrate:c(a,b+4)}}}};SAMPLERATE_TABLE=[96E3,88200,64E3,48E3,44100,32E3,24E3,22050,16E3,12E3,11025,8E3];this.Mp4=function(a){this.bytes=s(a,ArrayBuffer)?new Uint8Array(a):a;this.cache={}};this.Mp4.prototype={parse:function(){return this.cache.tree?
this.cache.tree:this.cache.tree=a(this.bytes,-8,this.bytes.length)},extractAACAsArrayBuffer:function(){var a=this.parse().moov.trak,b,c,d,e,h,j,i,p,k,l,m,r,q,u=0,n=0,t=new Uint8Array(new ArrayBuffer(7));if(s(a,Array))a.forEach(function(a){"soun"===a.mdia.hdlr.type&&(b=a)});else if("soun"===a.mdia.hdlr.type)b=a;else throw"This file does not have audio files.";a=b.mdia.minf.stbl.stsd.mp4a;c=b.mdia.minf.stbl.stsc.body;d=b.mdia.minf.stbl.stsz.body;e=b.mdia.minf.stbl.stco.body;q=new Uint8Array(7*d.length+
d.reduce(function(a,b){return a+b}));t[0]=255;t[1]=249;t[2]=64|SAMPLERATE_TABLE.indexOf(a.sampleRate)<<2|a.channels>>2;t[6]=252;for(h=0,r=0,p=c.length;h<p;++h){j=c[h].firstChunk-1;for(k=h+1<p?c[h+1].firstChunk-1:e.length;j<k;++j){n=e[j];for(i=0,l=c[h].samplesPerChunk;i<l;++i,++r)m=d[r]+7,t[3]=a.channels<<6|m>>11,t[4]=m>>3,t[5]=m<<5|31,q.set(t,u),u+=7,q.set(this.bytes.subarray(n,n+=d[r]),u),u+=d[r]}}return q.buffer},extractAACAsBlob:function(){var a=new e;a.append(this.extractAACAsArrayBuffer());return a.getBlob("audio/aac")}};
this.aacToM4a=function(a){function b(a){return(c[a+3]&3)<<11|c[a+4]<<3|c[a+5]>>5}var c=new Uint8Array(a),d=0,a=0,e=[],h=[],i=Date.now(),n,p,k,l,m,r,s,u,v,t,w,x;n=SAMPLERATE_TABLE[(c[2]&60)>>2];for(k=(c[2]&1)<<2|c[3]>>6;d<c.length;)h[a]=d,e[a++]=b(d)-7,d+=b(d);d=a;l=self.descr.createInitialObjectDescriptor(1,0,null,255,255,41,255,255);p=new Uint8Array(2);q(p,4096|SAMPLERATE_TABLE.indexOf(n)<<7|k<<3,0);k=self.descr.createDecoderSpecificInfo(p);p=self.descr.createDecodeConfigDescriptor(103,5,0,0,0,0,
[k]);k=self.descr.createSLConfigDescriptor(2);k=self.descr.createESDescriptor(0,0,null,null,p,k,[]);k=self.box.createEsdsBox(k);p=self.box.createMp4aBox(1,n,k);k=self.box.createFtypBox("M4A ","isom","mp42");m=self.box.createSttsBox([{count:a,duration:1024}]);r=self.box.createStscBox(a,d);s=self.box.createStszBox(0,e);u=self.box.createStsdBox(p);v=self.box.createDinfBox(self.box.createUrlBox(null,1));t=self.box.createBox(16,"smhd");w=self.box.createMdhdBox(i,i,n,1024*a);x=self.box.createHdlrBox("soun",
"mp4.js Audio Handler");p=self.box.createTkhdBox(i,i,1,~~(614400*a/n));l=self.box.createIodsBox(l);n=self.box.createMvhdBox(i,i,600,~~(614400*a/n),2);i=e.reduce(function(a,b){return a+b});dataStart=k.length+m.length+r.length+s.length+u.length+v.length+t.length+w.length+x.length+p.length+l.length+n.length;dataStart+=48;dataStart+=4*(~~(e.length/d)+1)+16;d=self.box.createStcoBox([dataStart,dataStart+i]);d=self.box.concatBoxes("stbl",u,m,r,s,d);d=self.box.concatBoxes("minf",t,v,d);d=self.box.concatBoxes("mdia",
w,x,d);d=self.box.concatBoxes("trak",p,d);moov=self.box.concatBoxes("moov",n,l,d);d=self.box.createBox(i+8,"mdat");i=0;n=8;for(l=0;l<a;++l)i=h[l],d.set(c.subarray(i+7,i+7+e[l]),n),n+=e[l];a=self.box.createFreeBox("Produced with mp4.js "+self.version);return j(k,moov,d,a).buffer}}).call(this.mp4js,this);
